controllers/producto_controller.py
from flask import request, redirect, url_for, Blueprint

from models.producto_model import Producto
from views import producto_view

producto_bp = Blueprint('producto', __name__, url_prefix='/productos')

@producto_bp.route('/')
def index():
    # Obtener todos los usuarios
    productos = Producto.get_all()
    return producto_view.list(productos)

@producto_bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        descripcion = request.form['descripcion']
        precio = request.form['precio']
        stock = request.form['stock']
        
        producto = Producto(descripcion,precio,stock)
        producto.save()
        return redirect(url_for('producto.index'))
    
    return producto_view.create()

@producto_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    producto = Producto.get_by_id(id)
    if request.method == 'POST':
        descripcion = request.form['descripcion']
        precio = request.form['precio']
        stock = request.form['stock']

        # actualizar usuario
        producto.update(descripcion=descripcion,precio=precio,stock=stock)
        return redirect(url_for('producto.index'))
    
    return producto_view.edit(producto)

@producto_bp.route('/delete/<int:id>')
def delete(id):
    producto = Producto.get_by_id(id)
    producto.delete()
    return redirect(url_for('producto.index'))

views/producto_view.py
from flask import render_template

def list(productos):
    return render_template("productos/index.html", productos=productos)

def create():
    return render_template("productos/create.html")

def edit(producto):
    return render_template("productos/edit.html",producto=producto)

templates/productos/create.html
{% extends 'base.html' %}

{% block title %}PRODUCTOS | CREATE{% endblock %}
{% block content %}
<h1>Registro de producto</h1>
<form action="{{ url_for('producto.create')}}" method="POST">
    <div class="mb-3">
        <label for="nombre" class="form-label">Descripcio</label>
        <input type="text" class="form-control" name="descripcion" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Precio</label>
        <input type="number" class="form-control" name="precio" min="0" step="0.01" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Cantidad</label>
        <input type="number" class="form-control" name="stock" required>
    </div>
    <button type="submit" class="btn btn-primary">Registrar producto</button>
</form>
{% endblock %}

templates/productos/edit.html
{% extends 'base.html' %}

{% block title %}PRODUCTOS | EDIT {% endblock %}
{% block content %}
<h1>Actualizar de productos</h1>
<form action="{{ url_for('producto.edit', id=producto.id)}}" method="POST">
    <div class="mb-3">
        <label for="" class="form-label">Descripcion</label>
        <input type="text" class="form-control" name="descripcion" value="{{ producto.descripcion }}" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Precio</label>
        <input type="number" class="form-control" name="precio" min="0" step="0.01"value="{{ producto.precio }}" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Cantidad</label>
        <input type="number" class="form-control" name="stock" value="{{ producto.stock }}" required>
    </div>
    <button type="submit" class="btn btn-primary">Actualizar producto</button>
</form>
{% endblock %}

templates/productos/index.html
{% extends 'base.html' %}

{% block title %}PRODUCTOS{% endblock %}

{% block content %}

<div class="container mt-4">
    <h1>Lista de productos</h1>
    <a href="{{ url_for('producto.create')}}" class="btn btn-success mb-3">Nuevo</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Descripcion</th>
                <th>Precio</th>
                <th>Stock</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in productos %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.descripcion }}</td>
                <td>{{ item.precio }}</td>
                <td>{{ item.stock }}</td>
                <td>
                    <a href="{{ url_for('producto.edit', id=item.id) }}" class="btn btn-sm btn-warning">Editar</a>
                </td>
                <td>
                    <a href="{{ url_for('producto.delete', id=item.id) }}" class="btn btn-sm btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}