controllers/usuario_controller.py
from flask import request, redirect, url_for, Blueprint

from models.usuario_model import Usuario
from views import usuario_view

usuario_bp = Blueprint('usuario', __name__, url_prefix='/usuarios')

@usuario_bp.route('/')
def index():
    # Obtener todos los usuarios
    usuarios = Usuario.get_all()
    return usuario_view.list(usuarios)

@usuario_bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        nombre = request.form['nombre']
        username = request.form['username']
        password = request.form['password']
        rol = request.form['rol']
        
        usuario = Usuario(nombre,username,password,rol)
        usuario.save()
        return redirect(url_for('usuario.index'))
    
    return usuario_view.create()

@usuario_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    usuario = Usuario.get_by_id(id)
    if request.method == 'POST':
        nombre = request.form['nombre']
        username = request.form['username']
        password = request.form['password']
        rol = request.form['rol']
        # actualizar usuario
        usuario.update(nombre=nombre, username=username, password=password, rol=rol)
        return redirect(url_for('usuario.index'))
    
    return usuario_view.edit(usuario)

@usuario_bp.route('/delete/<int:id>')
def delete(id):
    usuario = Usuario.get_by_id(id)
    usuario.delete()
    return redirect(url_for('usuario.index'))

views/usuario_view.py
from flask import render_template

def list(usuarios):
    return render_template("usuarios/index.html", usuarios=usuarios)

def create():
    return render_template("usuarios/create.html")

def edit(usuario):
    return render_template("usuarios/edit.html", usuario=usuario)

templates/usuarios/create.html
{% extends 'base.html' %}

{% block title %}USUARIOS | CREATE{% endblock %}
{% block content %}
<h1>Registro de Usuario</h1>
<form action="{{ url_for('usuario.create')}}" method="POST">
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" class="form-control" name="nombre" required>
    </div>
    <div class="mb-3">
        <label for="nombre" class="form-label">Usuario</label>
        <input type="text" class="form-control" name="username" required>
    </div>
    <div class="mb-3">
        <label for="nombre" class="form-label">Password</label>
        <input type="text" class="form-control" name="password" required>
    </div>
    <div class="mb-3">
        <label for="nombre" class="form-label">Rol</label>
        <select name="rol" class="form-select">
            <option value="admin">Admin</option>
            <option value="cajero">Cajero</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Registrar Usuario</button>
</form>
{% endblock %}

templates/usuarios/edit.html
{% extends 'base.html' %}

{% block title %}USUARIOS | EDIT{% endblock %}
{% block content %}
<h1>Actualizar de Usuario</h1>
<form action="{{ url_for('usuario.edit', id=usuario.id)}}" method="POST">
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" class="form-control" name="nombre" value="{{ usuario.nombre }}" required>
    </div>
    <div class="mb-3">
        <label for="nombre" class="form-label">Usuario</label>
        <input type="text" class="form-control" name="username" value="{{ usuario.username }}" required>
    </div>
    <div class="mb-3">
        <label for="nombre" class="form-label">Password</label>
        <input type="text" class="form-control" name="password">
    </div>
    <div class="mb-3">
        <label for="nombre" class="form-label">Rol</label>
        <select name="rol" class="form-select">
            <option value="admin" {%if usuario.rol == 'admin'%}select{%endif%}>Admin</option>
            <option value="cajero" {%if usuario.rol == 'cajero'%}select{%endif%}>Cajero</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Registrar Usuario</button>
</form>
{% endblock %}

templates/usuarios/index.html
{% extends 'base.html' %}

{% block title %}USUARIOS{% endblock %}

{% block content %}

<div class="container mt-4">
    <h1>Lista de usuarios</h1>
    <a href="{{ url_for('usuario.create')}}" class="btn btn-success mb-3">Nuevo</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Username</th>
                <th>Rol</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in usuarios %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.nombre }}</td>
                <td>{{ item.username }}</td>
                <td>{{ item.rol }}</td>
                <td>
                    <a href="{{ url_for('usuario.edit', id=item.id) }}" class="btn btn-sm btn-warning">Editar</a>
                </td>
                <td>
                    <a href="{{ url_for('usuario.delete', id=item.id) }}" class="btn btn-sm btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}