controllers/venta_controller.py
from flask import request, redirect, url_for, Blueprint
from datetime import datetime

from models.venta_model import Venta
from models.producto_model import Producto
from models.cliente_model import Cliente

from views import venta_view

venta_bp = Blueprint('venta', __name__, url_prefix='/ventas')

@venta_bp.route('/')
def index():
    # Obtener todos los usuarios
    venta = Venta.get_all()
    return venta_view.list(venta)

@venta_bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        cliente_id = request.form['cliente_id']
        producto_id = request.form['producto_id']
        cantidad = request.form['cantidad']
        fecha_str = request.form['fecha']
        
        fecha = datetime.strptime(fecha_str,'%Y-%m-%d').date()

        venta = Venta(cliente_id=cliente_id,producto_id=producto_id,cantidad=cantidad,fecha=fecha)
        venta.save()
        return redirect(url_for('venta.index'))
    #datos para el formulario
    clientes = Cliente.query.all()
    productos = Producto.query.all()

    return venta_view.create(clientes, productos)

@venta_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    venta = Venta.get_by_id(id)
    if request.method == 'POST':
        cliente_id = request.form['cliente_id']
        producto_id = request.form['producto_id']
        cantidad = request.form['cantidad']
        fecha_str = request.form['fecha']
        
        fecha = datetime.strptime(fecha_str,'%Y-%m-%d').date()
    
        # actualizar usuario
        venta.update(cliente_id=cliente_id, producto_id=producto_id,cantidad=cantidad,fecha=fecha)
        return redirect(url_for('venta.index'))
    
    clientes = Cliente.query.all()
    productos = Producto.query.all()
    
    return venta_view.edit(venta, clientes, productos)

@venta_bp.route('/delete/<int:id>')
def delete(id):
    venta = Venta.get_by_id(id)
    venta.delete()
    return redirect(url_for('venta.index'))

views/venta_view.py
from flask import render_template

def list(ventas):
    return render_template("ventas/index.html", ventas=ventas)

def create(clientes,productos):
    #se requiere prooductos y clientes
    return render_template("ventas/create.html",clientes=clientes,productos=productos)

def edit(venta,clientes,productos):
    #serequiere productos y clientes
    return render_template("ventas/edit.html",venta=venta,clientes=clientes,productos=productos)

templates/ventas/create.html
{% extends 'base.html' %}

{% block title %}VENTAS | CREATE{% endblock %}
{% block content %}
<h1>Registro de ventas</h1>

<form action="{{ url_for('venta.create')}}" method="POST">
    <div class="mb-3">
        <label for="" class="form-label">Cliente</label>
        <select name="cliente_id" class="form-control" required>
            <option value="">Seleccione un cliente</option>
            {% for cliente in clientes %}
                <option value="{{ cliente.id }}">{{ cliente.nombre }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Producto</label>
        <select name="producto_id" class="form-control" required>
            <option value="">Seleccione un producto</option>
            {% for producto in productos %}
                <option value="{{ producto.id }}">{{ producto.descripcion }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Cantidad</label>
        <input type="number" class="form-control" name="cantidad" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Fecha</label>
        <input type="date" class="form-control" name="fecha" required>
    </div>
    <button type="submit" class="btn btn-primary">Registrar venta</button>
</form>
{% endblock %}

templates/ventas/edit.html
{% extends 'base.html' %}

{% block title %}VENTAS | EDITAR {% endblock %}
{% block content %}

<h1>Actualización de ventas</h1>

<form action="{{ url_for('venta.edit', id=venta.id) }}" method="POST">
    <div class="mb-3">
        <label for="" class="form-label">Cliente</label>
        <select name="cliente_id" class="form-control" required>
            <option value="">Seleccione un cliente</option>
            {% for cliente in clientes %}
                <option value="{{ cliente.id }}" {% if cliente.id == venta.cliente_id %}selected{% endif %}>
                    {{ cliente.nombre }}
                </option>
            {% endfor %}
        </select>
    </div>
    
    <div class="mb-3">
        <label for="" class="form-label">Producto</label>
        <select name="producto_id" class="form-control" required>
            <option value="">Seleccione un producto</option>
            {% for producto in productos %}
                <option value="{{ producto.id }}" {% if producto.id == venta.producto_id %}selected{% endif %}>
                    {{ producto.descripcion }}
                </option>
            {% endfor %}
        </select>
    </div>
    
    <div class="mb-3">
        <label for="" class="form-label">Cantidad</label>
        <input type="number" class="form-control" name="cantidad" value="{{ venta.cantidad }}" required>
    </div>
    
    <div class="mb-3">
        <label for="" class="form-label">Fecha</label>
        <input type="date" class="form-control" name="fecha" value="{{ venta.fecha.strftime('%Y-%m-%d') }}" required>
    </div>
    
    <button type="submit" class="btn btn-primary">Actualizar venta</button>
</form>

{% endblock %}

templates/ventas/index.html
{% extends 'base.html' %}

{% block title %}VENTAS{% endblock %}

{% block content %}

<h1>Lista de ventas</h1>
<a href="{{ url_for('venta.create')}}" class="btn btn-success mb-3">Nuevo</a>
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Cliente</th>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Fecha</th>
        <th></th>
        <th></th>
    </tr>
    {% for item in ventas %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.cliente.nombre }}</td>
            <td>{{ item.producto.descripcion }}</td>
            <td>{{ item.cantidad }}</td>
            <td>{{ item.fecha.strftime('%d/%m/%Y')}}</td>
            <td>
                <a href="{{ url_for('venta.edit', id=item.id) }}" class="btn btn-sm btn-warning">Editar</a>
            </td>
            <td>
                <a href="{{ url_for('venta.delete', id=item.id) }}" class="btn btn-sm btn-danger">Eliminar</a>
            </td>
        </tr>
            {% endfor %}
    </table>
{% endblock %}