controllers/cliente_controller.py
from flask import request, redirect, url_for, Blueprint

from models.cliente_model import Cliente
from views import cliente_view

cliente_bp = Blueprint('cliente', __name__, url_prefix='/clientes')

@cliente_bp.route('/')
def index():
    # Obtener todos los usuarios
    cliente = Cliente.get_all()
    return cliente_view.list(cliente)

@cliente_bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        nombre = request.form['nombre']
        email = request.form['email']
        telefono = request.form['telefono']
        
        cliente = Cliente(nombre,email,telefono)
        cliente.save()
        return redirect(url_for('cliente.index'))
    
    return cliente_view.create()

@cliente_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    cliente = Cliente.get_by_id(id)
    if request.method == 'POST':
        nombre = request.form['nombre']
        email = request.form['email']
        telefono = request.form['telefono']

        # actualizar usuario
        cliente.update(nombre=nombre,email=email,telefono=telefono)
        return redirect(url_for('cliente.index'))
    
    return cliente_view.edit(cliente)

@cliente_bp.route('/delete/<int:id>')
def delete(id):
    cliente = Cliente.get_by_id(id)
    cliente.delete()
    return redirect(url_for('cliente.index'))

views/cliente_view.py
from flask import render_template

def list(clientes):
    return render_template("clientes/index.html", clientes=clientes)

def create():
    return render_template("clientes/create.html")

def edit(cliente):
    return render_template("clientes/edit.html",cliente=cliente)

templates/clientes/create.html
{% extends 'base.html' %}

{% block title %}CLIENTES | CREATE{% endblock %}
{% block content %}
<h1>Registro de cliente</h1>
<form action="{{ url_for('cliente.create')}}" method="POST">
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" class="form-control" name="nombre" required>
    </div>
    <div class="mb-3">
        <label for="nombre" class="form-label">Correo Electronico</label>
        <input type="email" class="form-control" name="email" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Telefono</label>
        <input type="number" class="form-control" name="telefono" required>
    </div>
    <button type="submit" class="btn btn-primary">Registrar cliente</button>
</form>
{% endblock %}

templates/clientes/edit.html
{% extends 'base.html' %}

{% block title %}CLIENTES | EDIT{% endblock %}
{% block content %}
<h1>Actualizar de Clientes</h1>
<form action="{{ url_for('cliente.edit', id=cliente.id)}}" method="POST">
    <div class="mb-3">
        <label for="" class="form-label">Nombre</label>
        <input type="text" class="form-control" name="nombre" value="{{ cliente.nombre }}" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Correo Electronico</label>
        <input type="email" class="form-control" name="email" value="{{ cliente.email }}" required>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">telefono</label>
        <input type="telefono" class="form-control" name="telefono" value="{{ cliente.telefono }}" required>
    </div>
    <button type="submit" class="btn btn-primary">Actualizar Cliente</button>
</form>
{% endblock %}

templates/clientes/index.html
{% extends 'base.html' %}

{% block title %}CLIENTES{% endblock %}

{% block content %}

<div class="container mt-4">
    <h1>Lista de clientes</h1>
    <a href="{{ url_for('cliente.create')}}" class="btn btn-success mb-3">Nuevo</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>Telefono</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in clientes %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.nombre }}</td>
                <td>{{ item.email }}</td>
                <td>{{ item.telefono }}</td>
                <td>
                    <a href="{{ url_for('cliente.edit', id=item.id) }}" class="btn btn-sm btn-warning">Editar</a>
                </td>
                <td>
                    <a href="{{ url_for('cliente.delete', id=item.id) }}" class="btn btn-sm btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}